### ISSUE TITLE
VSCode 1.9.x broke breakpoint controls

### ISSUE THREAD

**Issue by intellix** [felixfbecker/vscode-php-debug#145] opened 2017-02-22 12:58 UTC
PHP version: 5.6.27
XDebug version: 2.4.1
Adapter version:  1.10.0

Your launch.json:  
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "localSourceRoot": "${workspaceRoot}/public",
      "port": 9000
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}

```
XDebug php.ini config:  
```
xdebug support => enabled
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 3 => 3
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.extended_info => On => On
xdebug.file_link_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.halt_level => 0 => 0
xdebug.idekey => no value => no value
xdebug.max_nesting_level => 256 => 256
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_aggregate => Off => Off
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => /var/tmp/ => /var/tmp/
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => On => On
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_handler => dbgp => dbgp
xdebug.remote_host => 127.0.0.1 => 127.0.0.1
xdebug.remote_log => no value => no value
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /var/tmp/ => /var/tmp/
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 1 => 1
```

After updating to VSCode 1.9.0 where the interface Terminal/Debug console etc changed slightly I noticed that I no longer get the controls along the top when I click "Start debugging". The arrow stays green despite debugging working. I can't Jump over etc as I don't have the controls anymore.

**Comment by felixfbecker** [comment] 2017-02-22 13:07
Can you post a screenshot/gif so I can see if this is a VS Code issue or a debugger issue?

**Comment by intellix** [comment] 2017-02-22 20:45
https://www.dropbox.com/s/06937kfhl42rde0/Screenshot%202017-02-08%2018.12.53.png?dl=0

> Andre Weinand @weinand Feb 08 18:16
> This looks like a crashed debug adapter (and VS Code does not pick up the crashed process correctly). Please file an issue against the php extension you are using.

**Comment by felixfbecker** [comment] 2017-02-22 21:01
Sorry, but what controls are you missing? The debugger controls are not on the left side of the window usually

**Comment by intellix** [comment] 2017-02-22 21:41
These controls: 
![debugging_actions](https://cloud.githubusercontent.com/assets/1162531/23233722/038520d4-f950-11e6-95cd-5a64d0fea69b.png)

**Comment by weinand** [comment] 2017-02-22 21:56
Could it be that the controls where accidentally moved off the window? We had a bug in that area that got fixed in 1.9.1 IIRC.

**Comment by felixfbecker** [comment] 2017-02-23 09:13
@intellix I figured you meant these, but your screenshot doesn't show the area where they usually are

**Comment by intellix** [comment] 2017-02-23 09:26
I can't see on any of the sides where the controls would be pushed off the side. I always had them in the middle of the editor and after upgrading to 1.9.0 they just outright disappeared so I can't control flow/debug anymore :(

In fact, they are shown for Node debugging sessions, so I suppose that means it's particular to this extension

**Comment by felixfbecker** [comment] 2017-02-23 09:26
That's weird. @weinand how could they get displayed in the node debugger but not in PHP?

**Comment by weinand** [comment] 2017-02-23 09:28
@isidorn could you help @intellix?

**Comment by isidorn** [comment] 2017-02-23 09:52
@intellix Sorry about that! Dup of #20298 which contains a workaround

**Comment by felixfbecker** [comment] 2017-02-23 09:56
Can I close this?

**Comment by intellix** [comment] 2017-02-23 10:05
Sure :) Thanks

**Comment by intellix** [comment] 2017-02-23 10:17
Actually, I just tried the supposed solution and it didn't seem to fix for me.
The value of `actionswidgetposition` was something like: `0.98`.
Deleted it, completely closed VSCode and re-opened and still nothing :) I'm using a 27" Thunderbolt display on OSX if that helps. I have it fully maximised and tried even increasing it more and looking around the edges. I'm not certain that it's caused by the widget position.

![screenshot 2017-02-23 11 14 37](https://cloud.githubusercontent.com/assets/1162531/23254786/8c8b43ea-f9b9-11e6-9c03-d2358758ab60.png)

**Comment by isidorn** [comment] 2017-02-23 10:18
@intellix can you please also try with VSCode insiders version

**Comment by felixfbecker** [comment] 2017-02-23 10:18
@isidorn can this in any way be related to the PHP debugger?

**Comment by isidorn** [comment] 2017-02-23 10:19
@felixfbecker should not be. 
@intellix do you also see it if you try debugging a simple javascript file e.g.
```
console.log('hello');
```

**Closed** 2017-02-23 10:21 UTC

**Comment by intellix** [comment] 2017-02-23 10:22
Ok, so this time I just went through the DOM of the editor and looked for the debug widget. I found it and it had a left value of -700px. I removed that positioning and it appeared again. I moved it back to the middle and now it appears every time :) I suppose it has nothing to do with vscode-php-debug.

No idea how it ended up there but I have it back again!

Thanks :)

**Comment by isidorn** [comment] 2017-02-23 10:25
Great. The issue is fixed in vscode insiders. And will also be available in the next stable release which should come out in a week or so
