### ISSUE TITLE
debugAdapterCrash, "Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by weinand** [felixfbecker/vscode-php-debug#204] opened 2017-11-21 17:06 UTC
_From @jmperro on November 21, 2017 17:2_

- VSCode Version: 1.18.1 x64
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Open folder with php files and php debug configurations
2. Press F5

The listening port of XDebug at php.ini and the launch.json is the same.
I've no other app listening on this port.

This is the error 
![2](https://user-images.githubusercontent.com/3727544/33085769-68bf15e6-cec4-11e7-940e-9d1be81fafb9.png)

_Copied from original issue: Microsoft/vscode#38895_

**Comment by DeanNonatomic** [comment] 2017-11-21 17:27
https://github.com/felixfbecker/vscode-php-debug/issues/149

**Comment by jmperro** [comment] 2017-11-21 17:39
Same as #203 please fix the v1.12 release.
Using the release v1.11.1

**Comment by felixfbecker** [comment] 2017-11-21 17:41
Closing this as a duplicate of #203

**Closed by felixfbecker** 2017-11-21 17:41 UTC
