### ISSUE TITLE
Better getting started guide

### ISSUE THREAD

**Issue by sandcastle** [felixfbecker/vscode-php-debug#20] opened 2016-03-02 08:50 UTC
For someone that is completely new to PHP (me), I struggled to get everything working on my mac and in the end had to give up and use PHP Storm to get a trivial task done.

Is there anyway that we can improve the docs for new starters?

Happy to help out, just don't know where to start.

**Comment by felixfbecker** [comment] 2016-03-02 09:10
@sandcastle Sure, maybe you can tell me were it could be improved / what the things were you did not understand?

**Comment by sandcastle** [comment] 2016-03-02 09:52
@felixfbecker the biggest gap was how I connected `xdebug` to php, the `xdebug` website doesn't have an easy getting started guide (unless I'm missing something?). I was also unsure if I needed something else to act as the web server to handle the requests.

**Comment by felixfbecker** [comment] 2016-03-02 10:02
@sandcastle The problem is that there are to many cases for me to cover in this guide if it should actually belong in the XDebug starting guide. There are differences between how to install it on Windows or Linux, there are differences if you use Apache or nginx, etc etc

**Comment by rguerreiro** [comment] 2016-03-26 18:35
I'm also a newbie and I'm trying to use it in Ubuntu with apache2. I'm also using the testproject from your repo. The launch.json is created just like the one you have and when I hit F5 VSCode keep saying to 'set up the launch configuration file to debug your application'. I simply don't know what to do next.

As far I know my XDebug is installed correctly, at least it show on my phpinfo().

**Comment by felixfbecker** [comment] 2016-03-27 16:25
@rguerreiro I can assure you this error is not generated from my adapter, it seems like a VS Code bug since I have heard the same error before. It seems like it can be resolved by restarting or deleting / recreating the launch.json. I would ask you to open an issue at Microsoft/vscode if the issue persist.

**Comment by felixfbecker** [comment] 2016-03-27 16:26
As for the original issue, @sandcastle do you think it would be helpful if I simply link to more documentation of the XDebug site?

**Comment by felixfbecker** [comment] 2016-03-31 13:45
@sandcastle @rguerreiro I updated the readme with more information on how to install XDebug and more links to the official docs. Please let me know if this makes it easier to get started or it is still missing something

**Comment by Andi-Lo** [comment] 2016-04-15 21:46
Do I have to use the port my Xampp Server is using (I have xampp running on port 80), or doesn't it matter what port i set in the launch.json? (e.g. you seem to use port 9000)

**Comment by felixfbecker** [comment] 2016-04-16 10:21
@Andi-Lo the port setting is the port over which this debug adapter communicates with XDebug, which is 9000 by default. You can change it in your php.ini by setting `xdebug.remote_port`. Port 80 is what your webserver is running on (default HTTP port). See https://xdebug.org/docs/all_settings#remote_port

**Closed** 2016-04-22 10:52 UTC
