### ISSUE TITLE
":Invalid variable attributes" reported in watch/eval

### ISSUE THREAD

**Issue by AnrDaemon** [felixfbecker/vscode-php-debug#393] opened 2020-02-27 15:05 UTC
PHP version:  7.1.31
XDebug version:  Xdebug v2.8.1
Adapter version: 1.13

Your launch.json:  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "XDebug",
            "type": "php",
            "request": "launch",
            "port": 9005,
            "stopOnEntry": true,
            "xdebugSettings": {
                "max_depth": 5,
                "max_children": 4096,
                "max_data": 1024,
                "show_hidden": 1,
                "extended_properties": 1,
                "multiple_sessions": 1
            },
            "pathMappings": {
                //"${workspaceFolder}": "${workspaceFolder}"
            }
        }
    ]
}
```

XDebug php.ini config:
```
xdebug.auto_trace	Off
xdebug.cli_color	0
xdebug.collect_assignments	Off
xdebug.collect_includes	Off
xdebug.collect_params	0
xdebug.collect_return	Off
xdebug.collect_vars	Off
xdebug.coverage_enable	Off
xdebug.default_enable	Off
xdebug.dump.COOKIE	no value
xdebug.dump.ENV	no value
xdebug.dump.FILES	no value
xdebug.dump.GET	no value
xdebug.dump.POST	no value
xdebug.dump.REQUEST	no value
xdebug.dump.SERVER	no value
xdebug.dump.SESSION	no value
xdebug.dump_globals	Off
xdebug.dump_once	Off
xdebug.dump_undefined	Off
xdebug.file_link_format	no value
xdebug.filename_format	no value
xdebug.force_display_errors	Off
xdebug.force_error_reporting	-1
xdebug.gc_stats_enable	Off
xdebug.gc_stats_output_dir	C:\Windows\Temp
xdebug.gc_stats_output_name	gcstats.%p
xdebug.halt_level	0
xdebug.idekey	cadumanh
xdebug.max_nesting_level	256
xdebug.max_stack_frames	-1
xdebug.overload_var_dump	2
xdebug.profiler_aggregate	Off
xdebug.profiler_append	Off
xdebug.profiler_enable	Off
xdebug.profiler_enable_trigger	Off
xdebug.profiler_enable_trigger_value	no value
xdebug.profiler_output_dir	C:\Windows\Temp
xdebug.profiler_output_name	cachegrind.out.%p
xdebug.remote_addr_header	no value
xdebug.remote_autostart	Off
xdebug.remote_connect_back	Off
xdebug.remote_cookie_expire_time	30
xdebug.remote_enable	On
xdebug.remote_handler	dbgp
xdebug.remote_host	localhost
xdebug.remote_log	...\xdebug.log
xdebug.remote_log_level	7
xdebug.remote_mode	req
xdebug.remote_port	9005
xdebug.remote_timeout	200
xdebug.scream	Off
xdebug.show_error_trace	Off
xdebug.show_exception_trace	Off
xdebug.show_local_vars	Off
xdebug.show_mem_delta	Off
xdebug.trace_enable_trigger	Off
xdebug.trace_enable_trigger_value	no value
xdebug.trace_format	0
xdebug.trace_options	0
xdebug.trace_output_dir	C:\Windows\Temp
xdebug.trace_output_name	trace.%c
xdebug.var_display_max_children	-1
xdebug.var_display_max_data	-1
xdebug.var_display_max_depth	-1
```

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):

Code snippet to reproduce:

```php
<?php

$itemDef = array (
  'PARENT_ID' => 'tb',
  'itemtype' => 'NewHidden',
  'model' => '{
    "value": "21"
}',
);

var_dump($itemDef);
```

Relevant XDebug response:
```xml
<response xmlns="urn:debugger_protocol_v1"
xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval"
transaction_id="366">
  <property type="array" children="1" numchildren="3" page="0"
  pagesize="4096">
    <property name="PARENT_ID" type="string" size="2"
    encoding="base64">
<![CDATA[dGI=]]>
    </property>
    <property name="itemtype" type="string" size="9"
    encoding="base64">
<![CDATA[TmV3SGlkZGVu]]>
    </property>
    <property type="string" size="21">
      <name encoding="base64">
<![CDATA[bW9kZWw=]]>
      </name>
      <value encoding="base64">
<![CDATA[ewogICAgInZhbHVlIjogIjIxIgp9]]>
      </value>
    </property>
  </property>
</response>
```
(Formatted for presentation)

The last array key (model) is failed to render.
This seems to be related to `"extended_properties": 1,` setting.

**Comment by zobo** [comment] 2021-05-07 08:40
Is there a reason you enabled `extended_properties`? I will add support, but I'm just wondering.

**Comment by AnrDaemon** [comment] 2021-05-07 09:26
I've been testing different options. In fact, I've been looking into encoding support, since project I've been debugging was in CP1251. But I checked the rest just in case.

**Comment by zobo** [comment] 2021-05-07 12:10
This branch should have support for extended properties. Can you try it? I can prepare a VSIX installer if you need.

**Comment by AnrDaemon** [comment] 2021-05-07 21:04
Yes, please, I don't have capability to build it myself.

**Comment by zobo** [comment] 2021-05-08 07:30
Here is a build of that branch. 
[php-debug-0.0.0-development.zip](https://github.com/xdebug/vscode-php-debug/files/6445426/php-debug-0.0.0-development.zip)

But the more I think about it, the more I don't think this will solve your specific issue. I'm guessing you have your strings in CP1251 encoding in PHP files, and then ask the browser to decode that with a header of Content-Type/charset. Since PHP itself has no idea about that encoding, and so Xdebug has no idea about that encoding, then also DBGp and this extension have no idea what's going on.. They expect UTF-8.

If that's all true, what could potentially be done is:
- see if there's somethin on PHP side that can be done - your PHP version is very old and unsupported, so NO
- see if there's a way to let Xdebug/DBGp handle all strings as specific charset - again, version outdated, unsupported, so NO
- special case in this vscode extension, to decode all variable strings when we get them over the network to UTF-8.

I'd be willing to try the lest point if you get me some example files, but since more or less everyone moved to UTF-8 I doubt there's much value in this, nor if it can be applied to a wider range of projects at all...

**Comment by AnrDaemon** [comment] 2021-05-11 17:31
I've tested with XDebug 3.0 and I'm unable to reproduce original case. Will need some more time to research, as my main testing platform is inaccessible right now.

Re: encoding
Let's not mix cases, shall we? There's at least two other issues regarding encoding #259 #251, but they seems both to point to array index encoding. If I won't find a more appropriate issue, and latest fixes won't cover my specific case, I'll file a new one.

**Comment by zobo** [comment] 2021-05-12 08:42
Ok. I can confirm that #251 is fixed by #566 - at least with my setups. I'll leave this open for now. If you can't reproduce it or if it's not relevant for you anymore feel free to close it.

**Comment by AnrDaemon** [comment] 2021-05-12 08:44
Sure. Thanks for support!

**Comment by zobo** [comment] 2021-06-07 13:04
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.16.0

**Closed as completed by zobo** 2021-06-07 13:04 UTC
