### ISSUE TITLE
Debugger doest not trigger break points 

### ISSUE THREAD

**Issue by AndrewKralovec** [felixfbecker/vscode-php-debug#82] opened 2016-11-09 22:18 UTC
PHP version:  
php 7.0
XDebug version:  
2.4
Adapter version:  

XDebug php.ini config:  
```
[PHP]
;;;;;;;;;;;;;;;;;;;
[XDebug]
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
zend_extension=/home/andrew/xdebug-2.4.0
; Local Variables:
; tab-width: 4
; End:
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${workspaceRoot}/test.php",
            "cwd": "/var/www/html/PHP/LAMP",
            "port": 9000
        }
    ]
}
```
XDebug logfile (from setting `xdebug.remote_log` in php.ini):  

zend_extension=/home/andrew/xdebug-2.4.0

Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```
<html>
<body>
<h1>A simple example</h1>

<?php
  phpinfo(); 
?>

</body>
</html>
```

So i set up the xdebug and tried running this debugger, but the break points done activate. 
Is there anything im missing ?

**Comment by felixfbecker** [comment] 2016-11-09 22:27
The XDebug logfile is in the issue template for a reason dude... cant help you like this

**Comment by AndrewKralovec** [comment] 2016-11-09 23:34
@felixfbecker Sorry, i dont see xdebug.remote_log in my php.ini

**Comment by felixfbecker** [comment] 2016-11-10 00:03
Yeah, you need to set it 😉

**Comment by AndrewKralovec** [comment] 2016-11-10 00:31
@felixfbecker Thank, sorry im new to xdebug. 
I added the remote log option, but i dont see the log appearing when i run the vscode debugger. 
[XDebug]
zend_extension="/home/andrew/xdebug-2.4.0"
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_host = 127.0.0.1
xdebug.remote_enable = 1
xdebug.remote_port = 9000
xdebug.remote_handler = dbgp
xdebug.remote_mode = req
xdebug.profiler_enable=0
xdebug.profiler_enable_trigger=1
xdebug.remote_autostart=1
xdebug.idekey=PHPSTORM
xdebug.remote_log="/home/andrew/Desktop/xdebug.log"

**Comment by felixfbecker** [comment] 2016-11-10 00:37
The log gets written to the file you specify

**Comment by AndrewKralovec** [comment] 2016-11-10 00:39
Yeah there is no xdebug.log in my Desktop after i run the vs debugger. Is there a step im missing?

**Comment by felixfbecker** [comment] 2016-11-10 01:00
If you are running a webserver as `www-data` it is unlikely it has write permissions to your desktop. Use something like `/var/log/xdebug.log` and make sure it can write to it

**Comment by AndrewKralovec** [comment] 2016-11-10 13:18
xdebug.remote_log="/var/log/xdebug.log"
Still no xdebug.log showing in the log dir

**Comment by AndrewKralovec** [comment] 2016-11-10 14:59
@felixfbecker Found it 

Log opened at 2016-11-10 00:39:02
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 00:39:02

Log opened at 2016-11-10 01:09:06
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 01:09:06

Log opened at 2016-11-10 01:39:03
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 01:39:03

Log opened at 2016-11-10 02:09:04
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 02:09:04

Log opened at 2016-11-10 02:39:02
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 02:39:02

Log opened at 2016-11-10 03:39:06
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 03:39:06

Log opened at 2016-11-10 04:09:06
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 04:09:06

Log opened at 2016-11-10 04:12:58
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 04:12:58

Log opened at 2016-11-10 13:09:23
I: Connecting to configured address/port: 127.0.0.1:9000.
E: Could not connect to client. :-(
Log closed at 2016-11-10 13:09:23

**Comment by AndrewKralovec** [comment] 2016-11-10 15:40
Also, now when i run the php command i get an error, if this helps. 

andrew@andrew-PC:/var/www/html/PHP/LAMP$ php test.php
Failed loading /home/andrew/xdebug-2.4.0:  /home/andrew/xdebug-2.4.0: cannot read file data: Is a directory
XDebug could not open the remote debug file '/var/log/xdebug.log'.

**Comment by felixfbecker** [comment] 2016-11-10 16:10
Your zend_extension doesn't seem to point to an extension file (.so) but to a directory.
I'm gonna close this as this clearly is a configuration issue with XDebug and not a bug in the adapter

**Closed by felixfbecker** 2016-11-10 16:10 UTC

**Comment by AndrewKralovec** [comment] 2016-11-10 16:35
Okay. Thanks, ill check out the xdebug website.

**Comment by AndrewKralovec** [comment] 2016-11-10 16:46
@felixfbecker  I dont know if this helpful to you or not but i got the debugger working. Turns out that your are suppose to set the Zend Module Api Nubmer for the extension path. 
Changed this 
`zend_extension=path/to/xdebug`
 to this
`zend_extension = /usr/lib/php/20151012/xdebug.so`

And it works now.

**Comment by felixfbecker** [comment] 2016-11-10 17:56
On linux, You need to set it to the path of the xdebug.so file. If you follow the instructions in the readme it will tell you this very precisely :wink:
