### ISSUE TITLE
Driver does not reply to xdebug break event on stepOver after breakpoint is reached

### ISSUE THREAD

**Issue by oxomoxo** [felixfbecker/vscode-php-debug#190] opened 2017-09-28 10:55 UTC
Hi there, 
xdebug and vscode driver worked beautifully untill yesterday (vscode 1.6.1 update)

XDebug seems to operate fine until a breakpoint is reached and it is requested a stepIn/Out or next or continue, in which case no answer seems to be received, debugger is still operational though (evaluteRequest is answered ok).

Something seen to be stuck in the pipe right now as xdebug waits for the driver to answer a downward break event ... I've got about 7K+ lines as below in the xdebug log file before it gets to a stop (timeout ?
 ~15s) :

```xml
< response 
	xmlns="urn:debugger_protocol_v1" 
	xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="break" reason="ok">
	<xdebug:message filename="file:///home/lorenzo/www/index.php" lineno="249"></xdebug:message>
</ response>

< response 
	xmlns="urn:debugger_protocol_v1" 
	xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="break" reason="ok">
	<xdebug:message filename="file:///home/lorenzo/www/index.php" lineno="249"></xdebug:message>
</ response>

< response 
	xmlns="urn:debugger_protocol_v1" 
	xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="stopping" reason="ok">
</ response>
```
And this is quite a blocking situation.

providing some log data :
[xdbgvscode.log](https://github.com/felixfbecker/vscode-php-debug/files/1340468/xdbgvscode.log)

and install details :

Linux 4.4.0-96-generic #119-Ubuntu x86_64 GNU/Linux

Xdebug v2.6.0-dev (now compiled/installed from plain github clone)

DBGp - Common DeBuGger Protocol Revision : 1.145 (from phpInfo())

VSCode : Version 1.16.1 Commit 27492b6bf3acb0775d82d2f87b25a93490673c6d

.vscode/extensions/felixfbecker.php-debug-1.11.1

.vscode/extensions/felixfbecker.php-intellisense-1.5.1

Thanks for any info on this ...
Lorenzo

**Comment by zobo** [comment] 2021-05-10 10:02
Never saw an issue like this. Since this is a very old Xdebug perhaps it has something to do with watches that can't evaluate.
I'll close this as irreproducable, but if you can get it to happen again please let me know and we'll try to work on it. Xdebug.log will also be needed.

**Closed as completed by zobo** 2021-05-10 10:02 UTC
Labels: irreproducable
